Feature/wsdev 1543 filter
cuweb/rds-tailwindui pull request #1
Opened 2022-10-06 12:17 UTC by HanqingZhou

2022-10-20 14:26 UTC, troychaplin requested changes
Cypress tests need to be updated

2022-10-20 15:27 UTC, HanqingZhou commented
> Cypress tests need to be updated



> Cypress tests need to be updated

Thank you Troy, cypress test has been updated to reflect current changes

2022-10-20 15:45 UTC, troychaplin approved these changes

2022-10-25 15:17 UTC, troychaplin approved these changes
Awesome stuff @HanqingZhou, this looks fantastic!

2022-10-25 15:17 UTC, merged